import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { readFile, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import test from "node:test";

const execFileAsync = promisify(execFile);
const generator = fileURLToPath(
  new URL("../scripts/generate-runtime-manifest.mjs", import.meta.url),
);
const validator = fileURLToPath(
  new URL("../scripts/validate-package-runtime-manifest.mjs", import.meta.url),
);
const archiveFiles = [
  "INSTALL.txt",
  "LICENSE",
  "LICENSE_WHATWG_SPECS",
  "NATIVE-LIBRARIES.txt",
  "README.md",
  "SOURCE.txt",
  "STASIS_UPSTREAM.toml",
  "THIRD_PARTY_LICENSES.html",
  "VERSION.txt",
  "controlled-web-session-v2.json",
  "session-v0.3-candidate.md",
  "stasis",
];

function manifest(): Record<string, unknown> {
  const version = "0.3.3";
  const artifact = (nodePlatform: string, nodeArch: string, releasePlatform: string) => {
    const root = `stasis-${version}-${releasePlatform}`;
    return {
      nodePlatform,
      nodeArch,
      releasePlatform,
      archiveUrl: `https://github.com/oxhq/stasis/releases/download/v${version}/${root}.tar.gz`,
      archiveSizeBytes: 123,
      archiveSha256: "a".repeat(64),
      archiveRoot: root,
      archiveFiles,
      executablePath: "stasis",
      executableSha256: "b".repeat(64),
    };
  };
  return {
    schema: 1,
    packageName: "@oxhq/stasis",
    sdkVersion: version,
    releaseTag: `v${version}`,
    implementation: {
      name: "stasis-shell",
      source: {
        servo_repository: "https://github.com/servo/servo.git",
        servo_revision: "1".repeat(40),
        pliego_repository: "https://github.com/oxhq/pliego.git",
        pliego_revision: "2".repeat(40),
        pliego_servo_merge_base: "3".repeat(40),
        stasis_repository: "https://github.com/oxhq/stasis.git",
        stasis_revision: "4".repeat(40),
      },
    },
    artifacts: {
      "linux-x64": artifact("linux", "x64", "linux-x86_64"),
      "darwin-arm64": artifact("darwin", "arm64", "macos-aarch64"),
    },
  };
}

function generatedModule(value: Record<string, unknown>): string {
  return `/* Generated by scripts/generate-runtime-manifest.mjs. Do not edit. */\nimport type { RuntimeDistributionManifest } from "./runtime-manifest.js";\n\nexport const RUNTIME_DISTRIBUTION_MANIFEST = ${JSON.stringify(value, null, 2)} as const satisfies RuntimeDistributionManifest;\n`;
}

test("runtime manifest generator is strict and deterministic", async (context) => {
  const directory = await mkdtemp(join(tmpdir(), "stasis-manifest-generator-test-"));
  context.after(() => rm(directory, { recursive: true, force: true }));
  const input = join(directory, "manifest.json");
  const first = join(directory, "first.ts");
  const second = join(directory, "second.ts");
  await writeFile(input, `${JSON.stringify(manifest(), null, 2)}\n`, "utf8");
  await execFileAsync(process.execPath, [generator, "--input", input, "--output", first]);
  await execFileAsync(process.execPath, [generator, "--input", input, "--output", second]);
  assert.equal(await readFile(first, "utf8"), await readFile(second, "utf8"));
  assert.match(await readFile(first, "utf8"), /NATIVE-LIBRARIES\.txt/u);

  await writeFile(input, '{"schema":1,"schema":1}\n', "utf8");
  await assert.rejects(
    execFileAsync(process.execPath, [generator, "--input", input, "--output", first]),
    /duplicate JSON object key/u,
  );
});

test("prepack validator binds the canonical manifest to the exact release package", async (context) => {
  const directory = await mkdtemp(join(tmpdir(), "stasis-manifest-prepack-test-"));
  context.after(() => rm(directory, { recursive: true, force: true }));
  const input = join(directory, "manifest.json");
  const generated = join(directory, "runtime-manifest.generated.ts");
  const packageFile = join(directory, "package.json");
  await writeFile(input, `${JSON.stringify(manifest(), null, 2)}\n`, "utf8");
  await execFileAsync(process.execPath, [generator, "--input", input, "--output", generated]);
  await writeFile(
    packageFile,
    `${JSON.stringify({ name: "@oxhq/stasis", version: "0.3.3" }, null, 2)}\n`,
    "utf8",
  );

  const result = await execFileAsync(process.execPath, [
    validator,
    "--package",
    packageFile,
    "--manifest",
    generated,
  ]);
  assert.equal(result.stdout, "validated @oxhq/stasis@0.3.3 runtime manifest\n");

  await writeFile(
    packageFile,
    `${JSON.stringify({ name: "@oxhq/stasis", version: "0.1.1" }, null, 2)}\n`,
    "utf8",
  );
  await assert.rejects(
    execFileAsync(process.execPath, [
      validator,
      "--package",
      packageFile,
      "--manifest",
      generated,
    ]),
    /must be bound exactly to @oxhq\/stasis@0\.1\.1/u,
  );

  await writeFile(
    packageFile,
    `${JSON.stringify({ name: "@oxhq/stasis", version: "0.3.3-alpha.1" }, null, 2)}\n`,
    "utf8",
  );
  await assert.rejects(
    execFileAsync(process.execPath, [
      validator,
      "--package",
      packageFile,
      "--manifest",
      generated,
    ]),
    /package version must be a stable three-part semantic version/u,
  );
});

test("prepack validator requires both release artifacts and the twelve-file inventory", async (context) => {
  const directory = await mkdtemp(join(tmpdir(), "stasis-manifest-shape-test-"));
  context.after(() => rm(directory, { recursive: true, force: true }));
  const packageFile = join(directory, "package.json");
  const generated = join(directory, "runtime-manifest.generated.ts");
  await writeFile(
    packageFile,
    `${JSON.stringify({ name: "@oxhq/stasis", version: "0.3.3" }, null, 2)}\n`,
    "utf8",
  );

  const missingLinux = manifest();
  const missingLinuxArtifacts = missingLinux.artifacts as Record<string, unknown>;
  delete missingLinuxArtifacts["linux-x64"];
  await writeFile(generated, generatedModule(missingLinux), "utf8");
  await assert.rejects(
    execFileAsync(process.execPath, [
      validator,
      "--package",
      packageFile,
      "--manifest",
      generated,
    ]),
    /artifacts has unexpected or missing fields/u,
  );

  const shortInventory = manifest();
  const artifacts = shortInventory.artifacts as Record<string, Record<string, unknown>>;
  artifacts["darwin-arm64"]!.archiveFiles = archiveFiles.slice(0, -1);
  await writeFile(generated, generatedModule(shortInventory), "utf8");
  await assert.rejects(
    execFileAsync(process.execPath, [
      validator,
      "--package",
      packageFile,
      "--manifest",
      generated,
    ]),
    /darwin-arm64 must bind the exact release archive inventory/u,
  );
});
